version: "2.4"
networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
services:
  # 中间件
  mysql:
    container_name: "${COMPOSE_PROJECT_NAME}_mysql" # disable scalability
    image: mysql:8
    networks:
      - network
    env_file:
      - env/mysql.env
    cap_add:
      - SYS_NICE  # solve the 'mbind: Operation not permitted' error
    volumes:
      - ./env/mysql-conf.d:/etc/mysql/conf.d
      - ./env/mysql-initdb.d:/docker-entrypoint-initdb.d
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/files:/var/lib/mysql-files
#    ports:
#      - "3306:3306"
    restart: always
  redis:
    container_name: "${COMPOSE_PROJECT_NAME}_redis"
    image: redis:alpine
    networks:
      - network
#    ports:
#      - "6379:6379"
    restart: always
  rabbit:
    container_name: "${COMPOSE_PROJECT_NAME}_rabbit"
    image: rabbitmq:management
    env_file:
      - env/rabbitmq.env
#    ports:
#      - "5672:5672"
#      - "15672:15672"
    networks:
      - network
    restart: always
  nacos:
    container_name: "${COMPOSE_PROJECT_NAME}_nacos"
    build:
      context: build/sduoj-nacos/2.1.2
    networks:
      - network
    env_file:
      - env/nacos.env
    volumes:
      - ./data/nacos-logs/:/home/nacos/logs
#    ports:
#      - "${NACOS_PORT8848}:8848"
#      - "${NACOS_PORT9848}:9848"
#      - "${NACOS_PORT9849}:9849"
    links:
      - "mysql:sduoj-mysql"
    environment:
      WAIT_HOSTS: sduoj-mysql:3306
    restart: always
  # 前端
  frontend:
    container_name: "${COMPOSE_PROJECT_NAME}_frontend"
    build:
      context: build/sduoj-frontend/latest
    networks:
      - network
    volumes:
      - ./env/frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    # 如需暴露 https，配置相应 ./env/frontend/ssl 目录下两个证书文件，并取消下面的注释
#      - ./env/frontend/ssl.conf:/etc/nginx/conf.d/ssl.conf:ro
#      - ./env/frontend/ssl:/etc/nginx/ssl:ro
    ports:
      - "${FRONTEND_PORT80}:80"
    # 如需暴露 https 的 443 端口，取消下面的注释
#      - "${FRONTEND_PORT443}:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    links:
      - "gateway:sduoj-gateway"
    restart: always
  # 后端网关
  gateway:
    container_name: "${COMPOSE_PROJECT_NAME}_gateway"
    image: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-server
    networks:
      - network
    volumes:
      - ./data/logs/:/root/sduoj/logs
    links:
      - "nacos:sduoj-nacos"
      - "redis:sduoj-redis"
    mem_limit: 2048M
    environment:
      WAIT_HOSTS: sduoj-nacos:8848
      NACOS_ADDR: sduoj-nacos:8848
      ACTIVE: prod
      SERVICE: gateway
    restart: on-failure
  # 后端微服务
  auth-service:
    image: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-server
    networks:
      - network
    volumes:
      - ./data/logs/:/root/sduoj/logs
    links:
      - "mysql:sduoj-mysql"
      - "nacos:sduoj-nacos"
    mem_limit: 2048M
    environment:
      WAIT_HOSTS: sduoj-mysql:3306,sduoj-nacos:8848
      NACOS_ADDR: sduoj-nacos:8848
      ACTIVE: prod
      SERVICE: auth
    restart: on-failure
  contest-service:
    image: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-server
    networks:
      - network
    volumes:
      - ./data/logs/:/root/sduoj/logs
    links:
      - "mysql:sduoj-mysql"
      - "redis:sduoj-redis"
      - "nacos:sduoj-nacos"
    mem_limit: 2048M
    environment:
      WAIT_HOSTS: sduoj-mysql:3306,sduoj-nacos:8848,sduoj-redis:6379
      NACOS_ADDR: sduoj-nacos:8848
      ACTIVE: prod
      SERVICE: contest
    restart: on-failure
  filesys-service:
    image: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-server
    networks:
      - network
    volumes:
      - ./data/logs/:/root/sduoj/logs
      - ./data/sduoj-filesys:/root/sduoj/filesys
    links:
      - "mysql:sduoj-mysql"
      - "nacos:sduoj-nacos"
    mem_limit: 2048M
    environment:
      WAIT_HOSTS: sduoj-mysql:3306,sduoj-nacos:8848
      NACOS_ADDR: sduoj-nacos:8848
      ACTIVE: prod
      SERVICE: filesys
    restart: on-failure
  problem-service:
    image: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-server
    networks:
      - network
    volumes:
      - ./data/logs/:/root/sduoj/logs
    links:
      - "mysql:sduoj-mysql"
      - "nacos:sduoj-nacos"
      - "redis:sduoj-redis"
      - "rabbit:sduoj-rabbit"
    mem_limit: 2048M
    environment:
      WAIT_HOSTS: sduoj-mysql:3306,sduoj-nacos:8848,sduoj-redis:6379,sduoj-rabbit:5672
      NACOS_ADDR: sduoj-nacos:8848
      ACTIVE: prod
      SERVICE: problem
    restart: on-failure
  submit-service:
    image: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-server
    networks:
      - network
    volumes:
      - ./data/logs/:/root/sduoj/logs
    links:
      - "mysql:sduoj-mysql"
      - "nacos:sduoj-nacos"
      - "redis:sduoj-redis"
      - "rabbit:sduoj-rabbit"
    mem_limit: 2048M
    environment:
      WAIT_HOSTS: sduoj-mysql:3306,sduoj-nacos:8848,sduoj-redis:6379,sduoj-rabbit:5672
      NACOS_ADDR: sduoj-nacos:8848
      ACTIVE: prod
      SERVICE: submit
    restart: on-failure
  user-service:
    image: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-server
    networks:
      - network
    volumes:
      - ./data/logs/:/root/sduoj/logs
    links:
      - "mysql:sduoj-mysql"
      - "nacos:sduoj-nacos"
      - "redis:sduoj-redis"
      - "rabbit:sduoj-rabbit"
    mem_limit: 2048M
    environment:
      WAIT_HOSTS: sduoj-mysql:3306,sduoj-nacos:8848,sduoj-redis:6379,sduoj-rabbit:5672
      NACOS_ADDR: sduoj-nacos:8848
      ACTIVE: prod
      SERVICE: user
    restart: on-failure
  websocket-service:
    image: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-server
    networks:
      - network
    volumes:
      - ./data/logs/:/root/sduoj/logs
    links:
      - "nacos:sduoj-nacos"
      - "redis:sduoj-redis"
      - "rabbit:sduoj-rabbit"
    mem_limit: 2048M
    environment:
      WAIT_HOSTS: sduoj-nacos:8848,sduoj-redis:6379,sduoj-rabbit:5672
      NACOS_ADDR: sduoj-nacos:8848
      ACTIVE: prod
      SERVICE: websocket
    restart: on-failure
  # 评测机
  judger:
    image: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-judger
    networks:
      - network
    links:
      - "nacos:sduoj-nacos"
      - "rabbit:sduoj-rabbit"
    pids_limit: 1024
    mem_limit: 1536M
    cpuset: "0"
    environment:
      WAIT_HOSTS: sduoj-nacos:8848,sduoj-rabbit:5672
      NACOS_ADDR: sduoj-nacos:8848
      ACTIVE: prod
    restart: on-failure
